title: super_fazai | super_fazai's Blog
name: super_fazai
email: superonesfazai@gmail.com
description: super_fazai，软件工程师，从事软件的开发工作。开源爱好者，GitHub:https://github.com/superonesfazai
keywords: super_fazai
skill_keywords: [Linux, Git, Android, 安全, python, 爬虫, sql, c/c++, 服务器, Rudy, Javascript, HTML+CSS, Swift, Laravel, Mac]

timezone:    PRC
encoding: "utf-8"

url: http://superonesfazai.github.io
baseurl:  "/"
domain:    superonesfazai.github.io
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/superonesfazai/superonesfazai.github.io

# Build settings
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

markdown:    kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  line_numbers: true

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-paginate

disqus:
  id: superonesfazai

google:
    analytics_id: UA-55452630-1

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: https://github.com/superonesfazai
    label: GitHub
    target: _blank

  -
    href: http://twitter.com
    label: twitter
    target: _blank

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

public_repositories: []
popular_repos: ['python', 'fzutils', 'fz_ip_pool']
contribute_repos: ['superonesfazai/python', 'superonesfazai/fzutils', 'superonesfazai/fz_ip_pool']
